{
 "title": "Kafka Consumer Application Metrics",
 "tags": [
  "kafka",
  "app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Throughput & Efficiency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Consumer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(app_kafka_events_received_count_total[1m])",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(app_kafka_events_processed_total[1m]))",
     "legendFormat": "Processed"
    },
    {
     "expr": "sum(rate(app_kafka_events_errors_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_kafka_events_processed_total{type=\"success\"}[5m])) / sum(rate(app_kafka_events_received_count_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Errors by Type (Last 1h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (increase(app_kafka_events_errors_total[1h]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Kafka Tuning Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Batch Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(app_kafka_events_batch_duration_seconds_sum[1m]) / rate(app_kafka_events_batch_duration_seconds_count[1m]) * 1000",
     "legendFormat": "Avg Batch Duration"
    }
   ]
  },
  {
   "title": "Message Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(app_kafka_event_received_size_bytes_sum[1m]) / rate(app_kafka_event_received_size_bytes_count[1m])",
     "legendFormat": "Avg Message Size"
    }
   ]
  },
  { "title": "Retries & DLT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "DLT Retry Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(app_kafka_events_retried_total[1m])",
     "legendFormat": "Retry Rate"
    }
   ]
  }
 ]
}